name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup guix
        run: |
            ls -al
            sudo apt update
            sudo apt install -y guix
            sudo guix archive --authorize < .github/workflows/keys/bordeaux.guix.gnu.org.pub
            sudo guix archive --authorize < .github/workflows/keys/berlin.guix.gnu.org.pub
            guix pull -C channels.scm
            guix describe

      - name: Build site
        run: |
          TARGET="$(guix build -f guix.scm)/www/site/"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: $TARGET

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
