name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/debdistutils/guix/container:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build haunt
        run: |
            groupadd --gid 0 root
            useradd --uid 0 --gid root --shell /bin/sh --home-dir / --system root
            cp -rL /gnu/store/*profile/etc/* /etc/
            groupadd --system guixbuild
            for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
            export HOME=/
            env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
            guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
            guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
            guix describe
            guix install libgpg-error
            GUIX_PROFILE="//.guix-profile"
            . "$GUIX_PROFILE/etc/profile"
            TARGET="$(guix build -f guix.scm)/www/site/"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: $TARGET

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
